### ISSUE TITLE
error with this terminal command: npm run build

### ISSUE THREAD

**Issue by mcferren** [vladotesanovic/angular2-express-slim#1]
> rimraf public/javascripts/app && tsc -w

sh: rimraf: command not found

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.10.32
npm ERR! npm  v2.11.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular2-express-slim@0.0.0 build: `rimraf public/javascripts/app && tsc -w`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular2-express-slim@0.0.0 build script 'rimraf public/javascripts/app && tsc -w'.
npm ERR! This is most likely a problem with the angular2-express-slim package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf public/javascripts/app && tsc -w
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-express-slim
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bmcferren/workspace/angular2-express-slim/npm-debug.log
Bens-MacBook-Pro:angular2-express-slim bmcferren$ npm start

> angular2-express-slim@0.0.0 start /Users/bmcferren/workspace/angular2-express-slim
> node ./bin/www

**Comment by vladotesanovic** [comment]
This is caused by different node versions. Node 5.1 install lot of things in node_modules, and one of them is rimram. Now i added that like dev dependencies.
