### ISSUE TITLE
Demo is always loading

### ISSUE THREAD

**Issue by robertobarroso** [vladotesanovic/angular2-express-slim#10]
Link to Heroku is always loading. I've cloned the project an run npm start and it continue happening.

I think something is missing.

**Comment by benjaminrancourt** [comment]
Hi,

Try running these scripts (from package.json): 
- `npm run bundle`
- `npm run bundle:prod`
- `npm run start`

Open http://localhost:3000/ and if the app is up and running, push the modified files to heroku: 
- `git add .`
- `git commit -m "New bundle.js files"`
- `git push heroku master`
- `heroku open`

I had the same problem and the new files solved it.

**Comment by kamalkech** [comment]
@ranb2002  good it's work, @vladotesanovic  must update README file.

but not compile automaticaly from ts to js

**Comment by misha130** [comment]
https://express-angular2-slim.herokuapp.com/ is always loading aswell

**Comment by vladotesanovic** [comment]
I changed the way how app is bundled and served, it should works now
