### ISSUE TITLE
Unhandled rejection Error on fetch for app/main.js 

### ISSUE THREAD

**Issue by MojtabaGhavidel** [vladotesanovic/angular2-express-slim#11]
i get this when running npm install : 

Unhandled rejection Error on fetch for app/main.js at file:///C:/wamp/Projects/1                 4.auth with express/app/main.js
        Error: ENOENT: no such file or directory, open 'C:\wamp\Projects\14.auth                  with express\app\main.js'
    at Error (native)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch                 okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                 1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"                 })

**Comment by MojtabaGhavidel** [comment]
I tried npm install 3 more times and it just worked.

**Comment by vladotesanovic** [comment]
persistence pays off :)
