### ISSUE TITLE
Where is the express?

### ISSUE THREAD

**Issue by jrgleason** [vladotesanovic/angular2-express-slim#6]
I like that you are trying to make the footprint as small as possible. However, you no longer include express ;-). Don't you think you should either re-add express or change the name of the project?

**Comment by vladotesanovic** [comment]
Nooo :) I am including it, you have it as deps in package.json

**Comment by jrgleason** [comment]
lol I missed that so I guess just not using it?

**Comment by jrgleason** [comment]
Ahhh no I missed user, is that still getting used lol?

**Comment by jrgleason** [comment]
Sorry got lost I thought we had reverted back to straight node... bad day lol

**Comment by vladotesanovic** [comment]
I just update that to rc.3 :) you can pull changes. Yea, i am still using it. There is no much stuff in node / express, just one route.... :(

**Comment by jrgleason** [comment]
I expanded it a little on my fork to include some stuff from the hero example on the ng2 site. I also created another app that includes NgMaterial 2 but is based off this one. Feel free to pull in whatever you want.
