### ISSUE TITLE
Disable distributables sourceMap

### ISSUE THREAD

**Issue by jselesan** [vladotesanovic/angular2-express-slim#7]
Hi there. I would like to know how to disable the distributables sourcemap fetching, in order load the app faster in development mode. I have to make a lot of reloads of the app I am developing, and it takes a couple of seconds to fetch all the sourcemaps
![seleccion_002](https://cloud.githubusercontent.com/assets/1767177/16396784/e031de5e-3c96-11e6-9e1e-1c328100d619.png)

**Comment by vladotesanovic** [comment]
No we can't disable that, because that are internal Angular 2 stuff ( RxJS ). 

Although, we can disable generating of the source maps for application files. But that will not speed up things much.

Source maps ( js.map ) files are meant for debugging ( are you using chrome debugger? )
